server:
  port: 8090
spring:
  servlet:
    multipart:
      enabled: true
      max-file-size: 10MB
      max-request-size: 10MB
  security:
    oauth2:
      resourceserver:
        jwt:
          issuer-uri: https://cognito-idp.${aws.region}.amazonaws.com/${aws.cognito.pool-id}
  datasource:
    url: jdbc:postgresql://localhost:5490/db-local
    username: postgres
    password: postgres
  jpa:
    hibernate:
      ddl-auto: update
allowed-origin: ${commons.web-url}
aws:
  region: ${AWS_REGION:eu-west-3}
  access-key: ${AWS_ACCESS_KEY_ID:}
  secret-key: ${AWS_ACCESS_KEY_SECRET:}
  cognito:
    pool-id: ${SPRING_COGNITO_USER_POOL_ID:}
    client-id: ${SPRING_COGNITO_CLIENT_ID:}
    client-secret: ${SPRING_COGNITO_CLIENT_SECRET:}

google:
  places:
    api-key: ${GOOGLE_PLACES_API_KEY:}

commons:
  web-url: http://localhost:5190
  backend-url: http://localhost:8090
  discord:
    channel-prefix: "dev-"

management:
  endpoints:
    jmx:
      exposure:
        exclude: null
        include: "*"
    web:
      exposure:
        include: "*"

sentry:
  enabled: false
  environment: dev

resend:
  enabled: true
  api-key: ${RESEND_API_KEY:}

stripe:
  api-key: ${STRIPE_API_KEY:}
  price-id: ${STRIPE_PRICE_ID:}
  price-id-annual: ${STRIPE_PRICE_ID_ANNUAL:}

logging:
  level:
    root: INFO
    com.kerflowapp.kerflow: DEBUG
    org.springframework: INFO
    org.hibernate: INFO
